/*
src:项目主要的代码资源
     common：各个页面共用的一些组件资源
         component：组件
         images：图片
         styles：共用组件的样式
     util：共用的多功能模块
     pages：各个页面
         page：页面模块
             component：页面使用的组件
             images：页面使用的图片
             styles：页面组件使用的样式
             views：具体页面
             index.js：子路由配置文件b，可以理解为`a/b`
     redux：redux相关
         actions：action相关
         reducers：reducer相关
         store：redux底层配置
     App.js：页面容器
     config.js：配置文件
     Main.js：主路由配置文件：a
     setup.js：初始化
 */

